<script setup>
import { ref, reactive } from 'vue';
import { useI18n } from 'vue-i18n';
import { Customer } from '../../domain/model/customer.entity.js';

const props = defineProps({
  visible: Boolean
});

const emit = defineEmits(['update:visible', 'save']);
const { t } = useI18n();

const documentTypes = [
  { label: 'DNI', value: 'DNI' },
  { label: 'RUC', value: 'RUC' },
  { label: 'C.E.', value: 'CE' },
  { label: 'Pasaporte', value: 'PASSPORT' }
];

const initialFormState = {
  documentType: 'DNI',
  documentNumber: '',
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  businessName: ''
};

const form = reactive({ ...initialFormState });
const isSubmitting = ref(false);

const close = () => {
  Object.assign(form, initialFormState);
  emit('update:visible', false);
};

const handleSave = async () => {
  isSubmitting.value = true;
  try {
    // In a real scenario, ID would be generated by the server or a UUID generator
    const tempId = Math.floor(Math.random() * 10000); 
    const newCustomer = new Customer(
      tempId,
      form.documentType,
      form.documentNumber,
      form.firstName,
      form.lastName,
      form.email,
      form.phone,
      form.businessName
    );
    
    emit('save', newCustomer);
    close();
  } finally {
    isSubmitting.value = false;
  }
};
</script>

<template>
  <pv-dialog 
    :visible="visible" 
    @update:visible="$emit('update:visible', $event)"
    :header="t('customers.form.title')" 
    :modal="true" 
    class="customer-form-dialog"
    :style="{ width: '500px' }"
    :draggable="false"
  >
    <div class="form-grid">
      <div class="form-field full-width">
        <label for="docType">{{ t('customers.form.document_type') }}</label>
        <pv-select 
          id="docType" 
          v-model="form.documentType" 
          :options="documentTypes" 
          optionLabel="label" 
          optionValue="value" 
          class="full-width"
        />
      </div>

      <div class="form-field full-width">
        <label for="docNumber">{{ t('customers.form.document_number') }}</label>
        <pv-input-text id="docNumber" v-model="form.documentNumber" class="full-width" />
      </div>

      <div class="form-field">
        <label for="firstName">{{ t('customers.form.first_name') }}</label>
        <pv-input-text id="firstName" v-model="form.firstName" class="full-width" />
      </div>

      <div class="form-field">
        <label for="lastName">{{ t('customers.form.last_name') }}</label>
        <pv-input-text id="lastName" v-model="form.lastName" class="full-width" />
      </div>

      <div class="form-field full-width">
        <label for="email">{{ t('customers.form.email') }}</label>
        <pv-input-text id="email" v-model="form.email" class="full-width" type="email" />
      </div>

      <div class="form-field full-width">
        <label for="phone">{{ t('customers.form.phone') }}</label>
        <pv-input-text id="phone" v-model="form.phone" class="full-width" />
      </div>

      <div class="form-field full-width" v-if="form.documentType === 'RUC'">
        <label for="businessName">{{ t('customers.form.business_name') }}</label>
        <pv-input-text id="businessName" v-model="form.businessName" class="full-width" />
      </div>
    </div>

    <template #footer>
      <div class="footer-actions">
        <pv-button 
          :label="t('customers.form.cancel')" 
          text 
          @click="close" 
          class="cancel-btn" 
        />
        <pv-button 
          :label="t('customers.form.save')" 
          @click="handleSave" 
          :loading="isSubmitting"
          class="save-btn" 
        />
      </div>
    </template>
  </pv-dialog>
</template>

<style scoped>
.customer-form-dialog :deep(.p-dialog-header) {
  padding: 2rem 2rem 1rem 2rem;
  font-family: 'Mona Sans', sans-serif;
}

.customer-form-dialog :deep(.p-dialog-title) {
  font-weight: 800;
  font-size: 1.5rem;
}

.form-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.25rem;
  padding: 0.5rem 0.5rem;
}

.form-field {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-field label {
  font-weight: 600;
  font-size: 0.9rem;
  color: #4b5563;
  font-family: 'Arimo', sans-serif;
}

.full-width {
  grid-column: span 2;
}

.full-width.p-inputtext, .full-width.p-select {
  width: 100%;
}

:deep(.p-inputtext), :deep(.p-select) {
  border-radius: 10px;
  border: 1px solid #d1d5db;
  padding: 0.75rem;
}

:deep(.p-inputtext:focus), :deep(.p-select:focus) {
  border-color: #0071EB;
  box-shadow: 0 0 0 3px rgba(0, 113, 235, 0.1);
}

.footer-actions {
  display: flex;
  justify-content: flex-end;
  gap: 1rem;
  padding: 1rem 1rem 1rem 1rem;
}

.save-btn {
  background: #0071EB;
  border: none;
  border-radius: 10px;
  padding: 0.75rem 2rem;
  font-weight: 600;
}

.cancel-btn {
  color: #6b7280;
  font-weight: 600;
}

.save-btn:hover {
  background: #0056b3 !important;
}
</style>
