<script setup>
import { onMounted, ref, computed } from 'vue';
import { useInventoryStore } from '../../application/inventory.store.js';
import { useI18n } from 'vue-i18n';
import { useToast } from 'primevue/usetoast';
import { Product } from '../../domain/model/product.entity.js';

const { t } = useI18n();
const inventoryStore = useInventoryStore();
const toast = useToast();
const searchQuery = ref('');
const selectedCategory = ref(null);
const filterMenu = ref(null);

// Dialog state
const displayDialog = ref(false);
const submitted = ref(false);
const newProduct = ref({
  name: '',
  sku: '',
  category: '',
  brand: '',
  unitPrice: 0,
  unitCost: 0,
  currentStock: 0,
  minimumStock: 0
});

onMounted(() => {
  inventoryStore.fetchProducts();
});

const handleSearch = () => {
  inventoryStore.filterProducts(searchQuery.value, selectedCategory.value);
};

const toggleFilterMenu = (event) => {
  filterMenu.value.toggle(event);
};

const setCategory = (category) => {
  selectedCategory.value = category;
  handleSearch();
};

const clearFilters = () => {
  searchQuery.value = '';
  selectedCategory.value = null;
  handleSearch();
};

const filterMenuItems = computed(() => {
  const items = [
    {
      label: 'Todas las categorías',
      icon: 'pi pi-th-large',
      command: () => setCategory(null)
    },
    { separator: true }
  ];

  inventoryStore.uniqueCategories.forEach(cat => {
    items.push({
      label: cat,
      icon: 'pi pi-tag',
      command: () => setCategory(cat)
    });
  });

  return items;
});

const openNew = () => {
  newProduct.value = {
    name: '',
    sku: '',
    category: '',
    brand: '',
    unitPrice: 0,
    unitCost: 0,
    currentStock: 0,
    minimumStock: 0
  };
  submitted.value = false;
  displayDialog.value = true;
};

const hideDialog = () => {
  displayDialog.value = false;
  submitted.value = false;
};

const saveProduct = async () => {
  submitted.value = true;

  if (newProduct.value.name.trim() && newProduct.value.sku.trim()) {
    try {
      const productEntity = new Product(
        null, // ID generated by backend
        newProduct.value.sku,
        newProduct.value.name,
        newProduct.value.category,
        newProduct.value.unitPrice,
        newProduct.value.unitCost,
        newProduct.value.currentStock,
        newProduct.value.minimumStock
      );
      
      // Injecting brand into the entity if we wanted to (the entity didn't have it explicitly before but I'll add it)
      productEntity.brand = newProduct.value.brand;

      await inventoryStore.addProduct(productEntity);
      
      toast.add({severity:'success', summary: 'Éxito', detail: 'Repuesto registrado', life: 3000});
      displayDialog.value = false;
      newProduct.value = {};
    } catch (err) {
      toast.add({severity:'error', summary: 'Error', detail: 'No se pudo registrar el repuesto', life: 3000});
    }
  }
};

const updateStock = async (product, delta) => {
  const newStock = Math.max(0, product.currentStock + delta);
  try {
    await inventoryStore.updateStock(product.id, newStock);
  } catch (err) {
    // Error handled by store
  }
};

const lowStockSummary = computed(() => {
  if (inventoryStore.lowStockProducts.length === 0) return '';
  return inventoryStore.lowStockProducts.slice(0, 3).map(p => p.name.split(' ').slice(0, 2).join(' ')).join(', ');
});
</script>

<template>
  <div class="inventory-container p-5">
    <pv-toast />
    
    <!-- Header -->
    <div class="flex justify-content-between align-items-center mb-4">
      <div class="flex-grow-1">
        <h1 class="text-4xl font-bold text-900 m-0">{{ t('inventory.title') }}</h1>
        <p class="text-500 font-medium m-0 mt-1">{{ inventoryStore.totalProducts }} {{ t('inventory.registered_products') }}</p>
      </div>
      <pv-button :label="t('inventory.add_product')" icon="pi pi-plus" class="p-button-primary border-round-lg shadow-2 px-4" @click="openNew" />
    </div>

    <!-- Low Stock Alert -->
    <div v-if="inventoryStore.lowStockCount > 0" class="low-stock-alert p-3 mb-5 flex align-items-center border-round-xl border-1 border-orange-200">
      <i class="pi pi-exclamation-triangle mr-3 text-orange-500 text-xl"></i>
      <span class="text-orange-900">
        <span class="font-bold text-orange-600">{{ inventoryStore.lowStockCount }} {{ t('inventory.low_stock_alert') }}:</span>
        <span class="ml-2 font-medium">{{ lowStockSummary }}...</span>
      </span>
    </div>

    <!-- Toolbar -->
    <div class="flex gap-3 mb-5 align-items-center">
      <pv-icon-field iconPosition="left" class="flex-grow-1">
        <pv-input-icon class="pi pi-search text-500"> </pv-input-icon>
        <pv-input-text 
          v-model="searchQuery" 
          @input="handleSearch"
          :placeholder="t('inventory.search_placeholder')" 
          class="w-full border-round-xl border-1 border-200 py-3 shadow-sm" 
        />
      </pv-icon-field>
      
      <div class="flex gap-2">
        <pv-button 
          v-if="selectedCategory || searchQuery" 
          icon="pi pi-filter-slash" 
          class="p-button-text p-button-secondary border-round-xl" 
          @click="clearFilters" 
        />
        <pv-button 
          icon="pi pi-filter" 
          :class="{'p-button-primary': selectedCategory, 'p-button-secondary p-button-outlined': !selectedCategory}"
          class="border-round-xl border-1 border-300 py-3 px-3 shadow-sm bg-white" 
          @click="toggleFilterMenu"
          aria-haspopup="true"
          aria-controls="filter_menu"
        />
        <pv-menu ref="filterMenu" id="filter_menu" :model="filterMenuItems" :popup="true" class="border-round-xl shadow-4" />
      </div>
    </div>

    <!-- Active Filters Badge -->
    <div v-if="selectedCategory" class="mb-4 flex align-items-center gap-2">
      <pv-tag :value="selectedCategory" severity="info" class="px-3 py-1 border-round-lg" icon="pi pi-tag" @click="setCategory(null)" style="cursor:pointer" />
      <span class="text-xs text-500">Filtrando por categoría</span>
    </div>

    <!-- Product Grid -->
    <div class="grid">
      <div v-for="product in inventoryStore.products" :key="product.id" class="col-12 md:col-6 lg:col-4 xl:col-3 p-2">
        <pv-card class="product-card border-round-xl shadow-1 hover:shadow-3 transition-all transition-duration-300 overflow-hidden" :class="{'low-stock-border': product.isLowStock()}">
          <template #content>
            <div class="flex justify-content-between align-items-start mb-3">
              <div class="product-icon flex align-items-center justify-content-center bg-blue-50 text-blue-500 border-round-lg w-3rem h-3rem">
                <i class="pi pi-box text-xl"></i>
              </div>
              <pv-tag 
                :value="product.isLowStock() ? t('inventory.status.low_stock') : t('inventory.status.ok')" 
                :severity="product.isLowStock() ? 'warn' : 'success'" 
                class="px-3"
              />
            </div>

            <div class="mb-3">
              <p class="text-xs text-500 uppercase font-medium m-0">{{ product.sku }} • {{ product.category }}</p>
              <h3 class="text-lg font-bold text-900 m-0 mt-1 line-height-2 h-3rem overflow-hidden">{{ product.name }}</h3>
              <p class="text-sm text-600 m-0 mt-1">{{ product.brand || 'Atelier' }}</p>
            </div>

            <div class="flex justify-content-between align-items-end mb-4">
              <div>
                <p class="text-xs text-500 m-0">{{ t('inventory.current_stock') }}</p>
                <div class="flex align-items-baseline gap-1">
                  <span class="text-2xl font-bold" :class="product.isLowStock() ? 'text-orange-500' : 'text-900'">{{ product.currentStock }}</span>
                  <span class="text-xs text-500">min: {{ product.minimumStock }}</span>
                </div>
              </div>
              <div class="text-right">
                <p class="text-xs text-500 m-0">{{ t('inventory.unit_price') }}</p>
                <p class="text-xl font-bold text-900 m-0">S/ {{ product.unitPrice }}</p>
              </div>
            </div>

            <div class="flex gap-2">
              <pv-button 
                icon="pi pi-minus" 
                class="p-button-secondary p-button-outlined flex-grow-1 border-round-lg" 
                @click="updateStock(product, -1)" 
                :loading="inventoryStore.isLoading && inventoryStore.updatingId === product.id"
              />
              <pv-button 
                icon="pi pi-plus" 
                class="p-button-secondary p-button-outlined flex-grow-1 border-round-lg" 
                @click="updateStock(product, 1)"
                :loading="inventoryStore.isLoading && inventoryStore.updatingId === product.id"
              />
            </div>
          </template>
        </pv-card>
      </div>
    </div>

    <!-- Product Registration Dialog -->
    <pv-dialog v-model:visible="displayDialog" :style="{width: '450px'}" :header="t('inventory.form.title')" :modal="true" class="p-fluid border-round-xl overflow-hidden">
      <div class="field mb-3">
        <pv-float-label>
          <pv-input-text id="name" v-model.trim="newProduct.name" required="true" autofocus :class="{'p-invalid': submitted && !newProduct.name}" class="border-round-lg" />
          <label for="name">{{ t('inventory.form.name') }}</label>
        </pv-float-label>
        <small class="p-error" v-if="submitted && !newProduct.name">{{ t('inventory.form.name') }} es requerido.</small>
      </div>

      <div class="field mb-3">
        <pv-float-label>
          <pv-input-text id="sku" v-model.trim="newProduct.sku" required="true" :class="{'p-invalid': submitted && !newProduct.sku}" class="border-round-lg" />
          <label for="sku">{{ t('inventory.form.sku') }}</label>
        </pv-float-label>
        <small class="p-error" v-if="submitted && !newProduct.sku">{{ t('inventory.form.sku') }} es requerido.</small>
      </div>

      <div class="formgrid grid">
        <div class="field col mb-3">
          <pv-float-label>
            <pv-input-text id="category" v-model="newProduct.category" class="border-round-lg" />
            <label for="category">{{ t('inventory.form.category') }}</label>
          </pv-float-label>
        </div>
        <div class="field col mb-3">
          <pv-float-label>
            <pv-input-text id="brand" v-model="newProduct.brand" class="border-round-lg" />
            <label for="brand">{{ t('inventory.form.brand') }}</label>
          </pv-float-label>
        </div>
      </div>

      <div class="formgrid grid">
        <div class="field col mb-3">
          <pv-float-label>
            <pv-input-number id="unitPrice" v-model="newProduct.unitPrice" mode="currency" currency="PEN" locale="es-PE" class="border-round-lg" />
            <label for="unitPrice">{{ t('inventory.form.unit_price') }}</label>
          </pv-float-label>
        </div>
        <div class="field col mb-3">
          <pv-float-label>
            <pv-input-number id="unitCost" v-model="newProduct.unitCost" mode="currency" currency="PEN" locale="es-PE" class="border-round-lg" />
            <label for="unitCost">{{ t('inventory.form.unit_cost') }}</label>
          </pv-float-label>
        </div>
      </div>

      <div class="formgrid grid">
        <div class="field col mb-3">
          <pv-float-label>
            <pv-input-number id="currentStock" v-model="newProduct.currentStock" class="border-round-lg" />
            <label for="currentStock">{{ t('inventory.form.current_stock') }}</label>
          </pv-float-label>
        </div>
        <div class="field col mb-3">
          <pv-float-label>
            <pv-input-number id="minimumStock" v-model="newProduct.minimumStock" class="border-round-lg" />
            <label for="minimumStock">{{ t('inventory.form.minimum_stock') }}</label>
          </pv-float-label>
        </div>
      </div>

      <template #footer>
        <pv-button :label="t('inventory.form.cancel')" icon="pi pi-times" class="p-button-text p-button-secondary border-round-lg" @click="hideDialog"/>
        <pv-button :label="t('inventory.form.save')" icon="pi pi-check" class="p-button-primary border-round-lg" @click="saveProduct" :loading="inventoryStore.isLoading" />
      </template>
    </pv-dialog>

    <!-- Loading State -->
    <div v-if="inventoryStore.isLoading && inventoryStore.products.length === 0" class="flex justify-content-center p-8">
      <i class="pi pi-spin pi-spinner text-4xl text-blue-500"></i>
    </div>

    <!-- Error State -->
    <div v-if="inventoryStore.error && !displayDialog" class="text-center p-4">
      <p class="text-red-500">{{ inventoryStore.error }}</p>
      <pv-button :label="t('common.retry')" icon="pi pi-refresh" @click="inventoryStore.fetchProducts" />
    </div>
  </div>
</template>

<style scoped>
.inventory-container {
  background-color: #f8fafc;
  min-height: 100%;
}

.low-stock-alert {
  background-color: #fff7ed;
  border: 1px solid #fed7aa;
}

.product-card {
  height: 100%;
  border: 1px solid #e2e8f0;
}

.product-card.low-stock-border {
  border-color: #fb923c;
}

.product-icon {
  background: #eff6ff;
}

:deep(.p-card-body) {
  padding: 1.25rem;
}

:deep(.p-inputtext) {
  background: white;
}

/* Custom hover effects for a premium feel */
.product-card:hover {
  transform: translateY(-4px);
}
</style>
